image: node:alpine

cache:
  paths:
    - node_modules

build:
  script: 
    - npm i
    - npm run ng -- build --base-href=/${CI_PROJECT_NAME}/
    - cp -r dist/${CI_PROJECT_NAME} public
  artifacts:
    paths:
      - public


pages:
  image: ubuntu
  stage: deploy
  script:
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
